### ISSUE TITLE
Crash in DetailsActivity

### ISSUE THREAD

**Issue by Kllin0219** [AliAsadi/Android-MVVM-Architecture#4]
Caused by: java.lang.ClassCastException: com.aliasadi.mvvm.data.domain.Movie cannot be cast to com.aliasadi.mvvm.data.model.MovieRemote
        at com.aliasadi.mvvm.ui.details.DetailsActivity.createViewModel(DetailsActivity.java:54)
        at com.aliasadi.mvvm.ui.details.DetailsActivity.createViewModel(DetailsActivity.java:26)
        at com.aliasadi.mvvm.ui.base.BaseActivity.onCreate(BaseActivity.java:20)
        at com.aliasadi.mvvm.ui.details.DetailsActivity.onCreate(DetailsActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:7845)
        at android.app.Activity.performCreate(Activity.java:7834)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3280)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3466) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:239) 
        at android.app.ActivityThread.main(ActivityThread.java:7500) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by gcasasbe7** [comment]
I've fixed it by creating a new mapping method inside MovieMapper to map a Movie object into a MovieRemote one. This fixes the crash @Kllin0219

**Comment by AliAsadi** [comment]
Thanks for the submission; The issue has been resolved.
